language: ruby
rvm:
#   - "1.8.7"
#   - "1.9.2"
#   - "1.9.3"
#   - jruby-18mode # JRuby in 1.8 mode
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx
    - rbx-2
# - jruby-master
# uncomment this line if your project needs to run something other than `rake`:
script: gem install minitest
# script: bundle exec install
script: ruby tests/test_simple_numbers.rb
 

# I added this while trying to get minitest to run
# Thanks :
# platforms rbx do
#    gem 'minitest' 
# end
